# Generated by Django 4.0.5 on 2022-06-27 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players_market', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='position',
            field=models.CharField(default='player', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='player',
            name='age',
            field=models.IntegerField(default=29),
        ),
    ]
