# Generated by Django 4.0.5 on 2022-06-29 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players_market', '0002_player_position_alter_player_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='team_value',
            field=models.FloatField(default=10000000),
        ),
        migrations.AlterField(
            model_name='player',
            name='age',
            field=models.IntegerField(default=32),
        ),
    ]
