# Generated by Django 4.0.5 on 2022-06-29 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players_market', '0003_team_team_value_alter_player_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_value',
            field=models.FloatField(default=20000000),
        ),
    ]
